### ISSUE TITLE
Привет, можем связаться? Есть готовый обход капчи.

### ISSUE THREAD

**Issue by egorchecpc** [The-One-Reborn-developer/BLS-bot#1]
Приветик, у меня по сути скрипт парсинга свободных дат готов, но я вообще fullstack web разработчик, и со скраперами опыт супер небольшой. У меня проблеммы с блоком доступа к странице после n-го числа запросов. Я понимаю, что в теории могу просто купить резидентские прокси, но хотелось бы пообщаться и возможно получить другое решение этого вопроса. Взамен поделюсь кодом капчи. Пиши в tg или на почту если интересно (пжлст, пжлст, пжлст)
tg: https://t.me/kryachev
email: egorchecpc@gmail.com

**Comment by The-One-Reborn-developer** [comment]
Issue closed.
